apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Release notes and upgrade instructions at:
  # https://github.com/reclaim-the-stack/opensearch-operator/releases
  - github.com/reclaim-the-stack/opensearch-operator/deploy?ref=v0.16.0
  - ./opensearch-servicemonitor.yaml

configMapGenerator:
  - name: opensearch-grafana-dashboard
    namespace: monitoring
    options:
      annotations:
        argocd.argoproj.io/sync-options: Replace=true
      labels:
        grafana_dashboard: "1"
    files:
      - dashboards/opensearch.json
generatorOptions:
  disableNameSuffixHash: true

# Uncomment to add Prometheus alerts for OpenSearch clusters
# components:
#   - ./alerts
