{
 "title": "Application",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(process_start_time_seconds{deployment!=\"\"}, namespace)"
    }
   },
   {
    "name": "deployment",
    "label": "Deployment",
    "query": {
     "query": "label_values(process_start_time_seconds{namespace=\"$namespace\"}, deployment)"
    }
   },
   {
    "name": "inbound",
    "query": {
     "query": "label_values(request_total{dst_namespace=\"$namespace\", dst_deployment=\"$deployment\"}, deployment)"
    }
   },
   {
    "name": "outbound",
    "query": {
     "query": "label_values(request_total{namespace=\"$namespace\", deployment=\"$deployment\"}, dst_deployment)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "SUCCESS RATE",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(response_total{classification=\"success\", namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\"}[$__rate_interval])) by (deployment) / sum(irate(response_total{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\"}[$__rate_interval])) by (deployment)",
     "legendFormat": "deploy/{{deployment}}"
    }
   ]
  },
  {
   "title": "REQUEST RATE",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(request_total{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\"}[$__rate_interval])) by (deployment)",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "LATENCY",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(irate(response_latency_ms_bucket{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\"}[$__rate_interval])) by (le, deployment))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(response_latency_ms_bucket{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\"}[$__rate_interval])) by (le, deployment))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "CPU USAGE",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(\n    node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=\"$deployment\", workload_type=\"deployment\"}\n) by (pod)\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "MEMORY USAGE",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(\n    container_memory_working_set_bytes{namespace=\"$namespace\", container!=\"\", image!=\"\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=\"$deployment\", workload_type=\"deployment\"}\n) by (pod)\n",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{pod=~\"$deployment-[^-]*-[^-]*$\"}) by (pod)",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "NETWORK TRAFFIC",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "(sum(irate(container_network_transmit_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=~\"$deployment\", workload_type=\"deployment\"}) by (deployment))",
     "legendFormat": "Outbound"
    },
    {
     "expr": "(sum(irate(container_network_receive_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload=~\"$deployment\", workload_type=\"deployment\"}) by (workload))\n",
     "legendFormat": "Inbound"
    }
   ]
  },
  {
   "title": "LOGS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "type": "logs",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "{app=\"$deployment\"} |= ``"
      }
     ]
    }
   ]
  },
  {
   "title": "INBOUND TCP Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "TCP CONNECTION FAILURES",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "tcp_close_total{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\",errno!=\"\"}",
       "legendFormat": "{{peer}} {{errno}}"
      }
     ]
    },
    {
     "title": "TCP CONNECTIONS OPEN",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "tcp_open_connections{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\"}",
       "legendFormat": "{{peer}}"
      }
     ]
    },
    {
     "title": "TCP CONNECTION DURATION",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
     "targets": [
      {
       "expr": "tcp_connection_duration_ms_bucket{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "$inbound",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "repeat": "inbound",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "SUCCESS RATE",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(irate(response_total{classification=\"success\", deployment=\"$inbound\", dst_namespace=\"$namespace\", dst_deployment=\"$deployment\", direction=\"outbound\"}[$__rate_interval])  > 0) by (pod) / sum(irate(response_total{deployment=\"$inbound\", dst_namespace=\"$namespace\", dst_deployment=\"$deployment\", direction=\"outbound\"}[$__rate_interval])  > 0) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "REQUEST RATE",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(irate(request_total{deployment!=\"\", deployment=\"$inbound\", dst_namespace=\"$namespace\", dst_deployment=\"$deployment\", direction=\"outbound\"}[$__rate_interval])) by (deployment, pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "LATENCY",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(response_latency_ms_bucket{deployment!=\"\", deployment=\"$inbound\", dst_namespace=\"$namespace\", dst_deployment=\"$deployment\", direction=\"outbound\"}[$__rate_interval])) by (le, deployment))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(response_latency_ms_bucket{deployment!=\"\", deployment=\"$inbound\", dst_namespace=\"$namespace\", dst_deployment=\"$deployment\", direction=\"outbound\"}[$__rate_interval])) by (le, deployment))",
       "legendFormat": "p95"
      }
     ]
    }
   ]
  },
  {
   "title": "OUTBOUND DEPLOYMENTS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "SUCCESS RATE",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(response_total{classification=\"success\", namespace=\"$namespace\", deployment=\"$deployment\", direction=\"outbound\"}[$__rate_interval]) > 0 or vector(1))  by (dst_deployment) / sum(rate(response_total{ namespace=\"$namespace\", deployment=\"$deployment\", direction=\"outbound\"}[$__rate_interval]) > 0  or vector(1))  by (dst_deployment)\n",
       "legendFormat": "deploy/{{dst_deployment}}"
      }
     ]
    },
    {
     "title": "REQUEST RATE",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(request_total{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"outbound\"}[$__rate_interval])) by (dst_deployment)",
       "legendFormat": "{{dst_deployment}}"
      }
     ]
    },
    {
     "title": "P95 LATENCY",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 19 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(response_latency_ms_bucket{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"outbound\"}[$__rate_interval])) by (le, dst_deployment))",
       "legendFormat": "P95 deploy/{{dst_deployment}}"
      }
     ]
    }
   ]
  },
  {
   "title": "OUTBOUND TCP Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "TCP CONNECTION FAILURES",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "tcp_close_total{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"outbound\",errno!=\"\"}",
       "legendFormat": "{{peer}} {{errno}}"
      }
     ]
    },
    {
     "title": "TCP CONNECTIONS OPEN",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tcp_open_connections{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"outbound\"}",
       "legendFormat": "{{peer}}"
      }
     ]
    },
    {
     "title": "TCP CONNECTION DURATION",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 32 },
     "targets": [
      {
       "expr": "tcp_connection_duration_ms_bucket{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"outbound\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "deploy/$outbound",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "repeat": "outbound",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "SUCCESS RATE",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(irate(response_total{classification=\"success\", namespace=\"$namespace\", deployment=\"$deployment\", dst_deployment=\"$outbound\", direction=\"outbound\"}[$__rate_interval]) >0) by (dst_deployment) / sum(irate(response_total{namespace=\"$namespace\", deployment=\"$deployment\", dst_deployment=\"$outbound\", direction=\"outbound\"}[$__rate_interval] )>0 ) by (dst_deployment)",
       "legendFormat": "deploy/{{dst_deployment}}"
      }
     ]
    },
    {
     "title": "REQUEST RATE",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(irate(request_total{namespace=\"$namespace\", deployment=\"$deployment\", dst_deployment=\"$outbound\", direction=\"outbound\"}[$__rate_interval])) by (dst_deployment)",
       "legendFormat": "{{dst_deployment}}"
      }
     ]
    },
    {
     "title": "LATENCY",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(response_latency_ms_bucket{namespace=\"$namespace\", deployment=\"$deployment\", dst_deployment=\"$outbound\", direction=\"outbound\"}[$__rate_interval])) by (le, dst_deployment))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(response_latency_ms_bucket{namespace=\"$namespace\", deployment=\"$deployment\", dst_deployment=\"$outbound\", direction=\"outbound\"}[$__rate_interval])) by (le, dst_deployment))",
       "legendFormat": "p95"
      }
     ]
    }
   ]
  }
 ]
}