apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: altinity-clickhouse-operator
  namespace: argocd
spec:
  project: platform
  source:
    chart: altinity-clickhouse-operator
    repoURL: https://docs.altinity.com/clickhouse-operator/
    targetRevision: 0.23.4
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true