# Creates a generic Deployment. Command to run must be configured via .deployments.%{name}.command.
#
# Example values.yaml:
# image: %{image}
# deployments:
#   %{camelName}:
#     replicas: 1
#     memory: 512Mi
#     cpu: 250m
#     env: [] # Put ENV which should only apply to the sidekiq deployment here
#     # command: <custom-command> (if you don't want to bundle exec sidekiq)
# envFrom:
#   - secretRef:
#       name: %{application} # Create a dedicated application secret with k secrets:create %{application}
# env: [] # Put ENV which applies to all deployments here

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-%{name}
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: {{ .Values.deployments.%{camelName}.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-%{name}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-%{name}
      annotations:
        linkerd.io/inject: enabled
        kubectl.kubernetes.io/default-container: sidekiq
    spec:
      containers:
        - name: sidekiq
          image: {{ .Values.image }}
          command:
            {{- range .Values.deployments.%{camelName}.command | default "bundle exec sidekiq" | split " " }}
            - {{ . | quote }}
            {{- end }}
          # NOTE: We avoid putting a limit on CPU since Kubernetes throttling kills performance and CPU averages
          # tends to be low, so we can allow some pods to burst when needed. Adjust as you see fit.
          resources:
            requests:
              memory: {{ .Values.deployments.%{camelName}.memory }}
              cpu: {{ .Values.deployments.%{camelName}.cpu }}
            limits:
              memory: {{ .Values.deployments.%{camelName}.memory }}
          envFrom: {{ .Values.envFrom | toYaml | nindent 12 }}
          env:
            {{- if .Values.env }}
            {{- .Values.env | toYaml | nindent 12 }}
            {{- end }}
            {{- if .Values.deployments.%{camelName}.env }}
            {{- .Values.deployments.%{camelName}.env | toYaml | nindent 12 }}
            {{- end }}
