apiVersion: apps/v1
kind: Deployment
metadata:
  name: gigapipe
  namespace: logging
spec:
  replicas: 1 # TODO: Increase to 2+ for HA
  selector:
    matchLabels:
      app: gigapipe
  template:
    metadata:
      labels:
        app: gigapipe
    spec:
      containers:
        - name: web
          image: ghcr.io/metrico/gigapipe:v4.1.0
          ports:
            - containerPort: 3100
          resources:
            requests:
              memory: 100Mi
              cpu: 100m
            limits:
              memory: 1Gi
          env:
            - name: CLICKHOUSE_SERVER
              value: clickhouse-gigapipe.logging.svc.cluster.local
            - name: CLICKHOUSE_AUTH
              value: gigapipe:gigapipe
            # Configure these to set how long you want to keep logs for:
            - name: LABELS_DAYS
              value: "30"
            - name: SAMPLES_DAYS
              value: "30"
---
apiVersion: v1
kind: Service
metadata:
  name: gigapipe
  namespace: logging
spec:
  type: ClusterIP
  ports:
    - port: 3100
      targetPort: 3100
      protocol: TCP
  selector:
    app: gigapipe
